server:
  port: 8082

spring:
  datasource:
    username: root
    password: zero
    url: jdbc:mysql://localhost:3306/department_db
  jpa:
    hibernate:
      ddl-auto: update
  boot:
    message: changed/update department service
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
